=== DeffersonCheng/frame/src/main/resources/pageDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="pageDefinition" attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pageDefinition" type="pageDefinitionType">
		<xs:annotation>
			<xs:documentation>
				随便写写
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="pageDefinitionType">
		<xs:sequence>
			<xs:element name="queryDefinition" minOccurs="1"
				maxOccurs="1" type="queryDefinitionType">
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="delete" type="deleteType"/>
			<xs:element name="manage" type="manageType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="searchDefinitionType">
		<xs:sequence minOccurs="1">
			<xs:element name="condition" type="conditionType">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="conditionType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="staticData"/>
		</xs:sequence>
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="alias"/>
		<xs:attribute name="operator" use="required" type="operatorType">
		</xs:attribute>
		<xs:attribute name="defaultValue"/>
		<xs:attribute name="inputType" type="editorType">
		</xs:attribute>
		<xs:attribute name="displayText" use="required"/>
		<xs:attribute name="selectTextField"/>
		<xs:attribute name="selectValeField"/>
		<xs:attribute name="inputId"/>
		<xs:attribute name="optionClass"/>
		<xs:attribute name="nullable" type="xs:boolean"/>
	</xs:complexType>
	<xs:simpleType name="operatorType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="="/>
			<xs:enumeration value="LIKE"/>
			<!--<xs:enumeration value="BETWEEN"></xs:enumeration> -->
			<xs:enumeration value="&gt;"/>
			<xs:enumeration value="&lt;"/>
			<xs:enumeration value="&gt;="/>
			<xs:enumeration value="&lt;="/>
			<xs:enumeration value="!="/>
			<xs:enumeration value="&lt;&gt;"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="queryDefinitionType">
		<xs:sequence>
			<xs:element minOccurs="1" name="mappedClass" type="mappedClassType"/>
			<xs:element name="where" minOccurs="0"/>
			<xs:element minOccurs="0" name="sort" type="sortType"/>
			<xs:element name="columns" minOccurs="1" maxOccurs="1" type="columnsType"/>
			<xs:element minOccurs="0" maxOccurs="1" name="pageSize" type="xs:int"/>
			<xs:element maxOccurs="1" minOccurs="0" name="js" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="css" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="1" name="searchDefinition" type="searchDefinitionType"/>
		</xs:sequence>
		<xs:attribute name="showIndex"/>
	</xs:complexType>
	<xs:complexType name="sortType">
		<xs:sequence>
			<xs:element minOccurs="0" name="by" type="sortByType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnsType">
		<xs:sequence>
			<xs:element minOccurs="1" name="column" type="columnType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sortByType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="fromAlias"/>
		<xs:attribute name="order" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ASC" />
					<xs:enumeration value="DESC" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="columnType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="header"/>
		<xs:attribute name="fromAlias"/>
		<xs:attribute name="width"/>
		<xs:attribute name="sortable" type="xs:boolean"/>
		<xs:attribute name="hidden" type="xs:boolean"/>
		<xs:attribute name="filter"/>
		<xs:attribute name="staticColumnData"/>
	</xs:complexType>
	<xs:complexType name="mappedClassType">
		<xs:sequence minOccurs="0">
			<xs:element name="join" type="joinType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mappedClass" use="required"/>
		<xs:attribute name="alias"/>
	</xs:complexType>
	<xs:complexType name="joinType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="as"/>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="LEFT" />
					<xs:enumeration value="INNER" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="manageType">
		<xs:sequence>
			<xs:element name="field" type="manageFieldType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="js" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="css" type="jscssType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="jscssType">
		<xs:sequence minOccurs="1">
			<xs:element name="path"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="editorType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="TEXT" />
			<xs:enumeration value="NUMBER" />
			<xs:enumeration value="SELECT" />
			<xs:enumeration value="DATEBOX" />
			<xs:enumeration value="TEXTAREA" />
			<xs:enumeration value="CHECKBOX" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="deleteType">
	</xs:complexType>
	<xs:complexType name="manageFieldType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="staticData"/>
		</xs:sequence>
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="defaultValue"/>
		<xs:attribute name="inputType" type="editorType"/>
		<xs:attribute name="displayText" use="required"/>
		<xs:attribute name="selectTextField"/>
		<xs:attribute name="selectValeField"/>
		<xs:attribute name="inputId"/>
		<xs:attribute name="optionClass"/>
		<xs:attribute name="nullable" type="xs:boolean">
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== DeffersonCheng/frame/src/main/java/com/frame/core/webapp/controller/account/rolePageDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition>
		<mappedClass mappedClass="com.frame.core.entity.RoleEntity"
			alias="r" >
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" fromAlias="r" order="ASC"></by>
		</sort>
		<columns>
			<column header="id" field="id" fromAlias="r" width="20%" sortable="true" hidden="false"></column>
			<column header="编码" field="code" fromAlias="r" width="40%" sortable="true" hidden="false"></column>
			<column header="名称" field="name" fromAlias="r" width="40%" sortable="true" hidden="false"></column>
		</columns>
		<searchDefinition>
			<condition alias="r" field="code" operator="LIKE" displayText="编码" inputType="TEXT"></condition>
			<condition alias="r" field="name" operator="LIKE" displayText="名称" inputType="TEXT"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
	</queryDefinition>
	<manage beforeManage="beforeUpdate">
		<field field="code" displayText="编码"></field>
		<field field="name" displayText="名称"></field>
		<field field="description" displayText="描述" inputType="TEXTAREA"></field>
		<js>
			<path>/resources/js/roleMenu/roleMenuManage.js</path>
			<path>/resources/ztree/js/jquery.ztree.all.js</path>
		</js>
		<css>
			<path>/resources/css/roleMenu/roleMenuManage.css</path>
			<path>/resources/ztree/css/metroStyle/metroStyle.css</path>
		</css>
	</manage>
	<delete beforeDelete="beforeDelete"></delete>
</pageDefinition>

=== DeffersonCheng/frame/schedule-application/src/main/java/com/frame/schedule/controller/taskRecordExceptionController.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:noNamespaceSchemaLocation="/pageDefinition.xsd">
	<queryDefinition>
		<mappedClass mappedClass="com.frame.schedule.entity.TaskExceptionEntity"
			alias="e" >
			<join type="LEFT" field="taskRecordEntity" as="r" />
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" order="ASC"/>
		</sort>
		<columns>
			<column header="Id" field="id" fromAlias="r" width="10%" sortable="true" hidden="false"/>
			<column header="执行编码" field="taskExecuteCode" fromAlias="r" width="10%" sortable="true" hidden="false"/>
			<column header="记录执行次数" field="recordExecuteCount" fromAlias="e" sortable="true" hidden="false"/>
			<column header="创建时间" field="createDateTime" fromAlias="r" sortable="true" hidden="false"/>
		</columns>

		<searchDefinition>
			<condition alias="r" field="createDateTime" operator="&gt;" displayText="发生时间" inputType="DATEBOX"/>
			<condition alias="r" field="createDateTime" operator="&lt;" displayText="--到--" inputType="DATEBOX"/>
			<condition alias="r" field="taskExecuteCode" operator="LIKE" displayText="执行编码" inputType="TEXT"/>
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
			<path>/resources/js/schedule/task-exception-list.js</path>
		</js>
        <css>
        </css>
	</queryDefinition>
	<delete></delete>
	<manage>
		<field field="id" displayText="ID"/>
		<field field="recordExecuteCount" displayText="记录执行次数"/>
		<field field="createDateTime" displayText="创建时间"/>
		<field field="content" displayText="详细信息" inputType="TEXTAREA"/>

		<js>
			<path>/resources/js/schedule/task-exception-manage.js</path>
		</js>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/webapp/controller/admin/editor/indexManageDefinetion.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.media.IndexShowEntity" alias="i">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.core.entity.UserEntity" alias="u">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<where>u.id=i.userId</where>
		<sort>
			<by field="createDateTime" fromAlias="i" order="DESC"></by>
		</sort>

		<columns>
			<column header="ID" field="id" fromAlias="i" width="10%" editorType="CHECKBOX" sortable="true" hidden="false"></column>
			<column header="创建 人" field="nickName" fromAlias="u" width="20%" sortable="true" hidden="false"></column>
			<column header="标题" field="title" fromAlias="i" width="20%" sortable="false" hidden="false"></column>
			<column header="状态" field="status" fromAlias="i" width="20%" sortable="false" hidden="false"></column>
<!-- 			<column header="内容" field="content" fromAlias="c" width="20%" sortable="false" hidden="false"></column>
	 -->	<column header="创建日期" field="createDateTime" fromAlias="i" width="20%" sortable="true" hidden="false"></column>
			<!-- <column header="操作" width="10%" sortable="false" hidden="false" staticColumnData="删除"></column> -->
		</columns>
		<searchDefinition>
			<condition alias="i" field="id" operator="=" displayText="ID" inputType="NUMBER"></condition>
			<condition alias="i" field="userId" operator="LIKE" displayText="创建 人" inputType="SELECT" selectTextField="nickName" selectValueField="id" optionClass="com.frame.core.entity.UserEntity"></condition>
			<condition alias="i" field="createDateTime" operator="&gt;" displayText="创建日期" inputType="DATEBOX"></condition>
			<condition alias="i" field="createDateTime" operator="&lt;" displayText="至" inputType="DATEBOX"></condition>
			<condition alias="i" field="title" operator="LIKE" displayText="标题" inputType="TEXT"></condition><!-- selectTextField="createUserKey" inputType="SELECT" -->
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
			<path>/resources/js/index/admin-index-manage-list.js</path>
		</js>
		<!-- <css><path>/a/b/c</path></css> -->
	</queryDefinition>
	<delete beforeDelete="beforeDelete"></delete>
	<manage beforeManage="beforeUpdate">
		<field field="title" inputId="edtitle" displayText="标题" ></field>
		<field field="status" inputId="edstatus" displayText="是否禁用" inputType="SELECT" nullable="false">
			<staticData>[{text:"是",value:"0"},{text:"否",value:"1"}]</staticData>
		</field>
		<field field="id" inputId="edid" hidden="true" displayText="" ></field>
		<field field="content" inputId="edcontent" displayText="" inputType="TEXTAREA"></field>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/etpl 3-2-0.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/umeditor.config.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/umeditor.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/lang/zh-cn/zh-cn.js</path>
			<path>/resources/js/index/index-manage.js</path>
		</js>
		<css>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/themes/default/css/umeditor-1-2-3.css</path>
		</css>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/webapp/controller/admin/img/adminImgGroupDefinetion.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.media.ImgGroupEntity" alias="m">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.core.entity.UserEntity" alias="u">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<where>u.id=m.createUserKey</where>
		<sort>
			<by field="id" fromAlias="m" order="ASC"></by>
		</sort>

		<columns>
			<column header="ID" field="id" fromAlias="m" width="10%" sortable="true" hidden="false"></column>
			<column header="创建 人" field="nickName" fromAlias="u" width="20%" sortable="true" hidden="false"></column>
			<column header="相册名称" field="imgGroupName" fromAlias="m" width="20%" sortable="false" hidden="false"></column>
			<column header="创建日期" field="createDateTime" fromAlias="m" width="20%" sortable="true" hidden="false"></column>
			<!-- <column header="操作" width="10%" sortable="false" hidden="false" staticColumnData="删除"></column> -->
		</columns>
		<searchDefinition>
			<condition alias="m" field="id" operator="=" displayText="ID" inputType="NUMBER"></condition>
			<condition alias="m" field="createUserKey" operator="LIKE" displayText="创建 人" inputType="SELECT" selectTextField="nickName" selectValueField="id" optionClass="com.frame.core.entity.UserEntity"></condition>
			<condition alias="m" field="createDateTime" operator="&gt;" displayText="创建日期" inputType="DATEBOX"></condition>
			<condition alias="m" field="createDateTime" operator="&lt;" displayText="至" inputType="DATEBOX"></condition>
			<condition alias="m" field="imgGroupName" operator="LIKE" displayText="相册名称" inputType="TEXT"></condition><!-- selectTextField="createUserKey" inputType="SELECT" -->
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/js/img/img-group-list.js</path>
		</js>
		<!-- <css><path>/a/b/c</path></css> -->
	</queryDefinition>
	<delete beforeDelete="beforeDelete"></delete>
	<manage beforeManage="beforeUpdate">
		<field field="imgGroupName" displayText="相册名称"></field>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/schedule/controller/taskController.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:noNamespaceSchemaLocation="/pageDefinition.xsd">
	<queryDefinition>
		<mappedClass mappedClass="com.frame.schedule.entity.TaskEntity">
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" order="ASC"></by>
		</sort>
		<columns>
			<column header="任务编码" field="taskCode"  width="10%" sortable="true" hidden="false"></column>
			<column header="任务名称" field="taskName" sortable="true" hidden="false"></column>
			<column header="任务执行周期" field="taskCron" sortable="true" hidden="false"></column>
			<column header="执行次数" field="execNum" sortable="true" hidden="false"></column>
			<column header="状态" field="status" sortable="true" hidden="false"></column>
			<column header="创建时间" field="createDateTime" sortable="true" hidden="false"></column>
			<column header="更新时间" field="updateDateTime" sortable="true" hidden="false"></column>
		</columns>
		<searchDefinition>
			<condition field="taskCode" operator="LIKE" displayText="任务编码" inputType="TEXT"></condition>
			<condition field="taskName" operator="LIKE" displayText="任务名称" inputType="TEXT"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
        <js>
            <path>/resources/js/schedule/task-list.js</path>
        </js>
        <css>
        </css>
	</queryDefinition>
	<delete></delete>
	<manage>
		<field field="taskName" displayText="任务名称"></field>
		<field field="taskCode" displayText="任务编码"></field>
		<field field="taskCron" displayText="任务执行周期"></field>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/core/webapp/controller/account/pageDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.core.entity.UserEntity"
			alias="u" >
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" fromAlias="u" order="ASC"></by>
		</sort>
		<columns>
			<column header="用户名" field="userLoginVerification" fromAlias="u" width="40%" sortable="true" hidden="false"></column>
			<column header="昵称" field="nickName" fromAlias="u" width="40%" sortable="true" hidden="false"></column>
		</columns>
		<searchDefinition>
			<condition alias="u" field="userLoginVerification" operator="LIKE" displayText="用户名" inputType="TEXT"></condition>
			<condition alias="u" field="nickName" operator="LIKE" displayText="昵称" inputType="TEXT"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
	</queryDefinition>
	<manage beforeManage="beforeUpdate">
		<field field="userLoginVerification" displayText="用户名"></field>
		<field field="nickName" displayText="昵称"></field>
		<field field="roles" displayText="拥有角色" inputType="CHECKBOX" optionClass="com.frame.core.entity.RoleEntity" selectTextField="name" selectValeField="id"></field>
	</manage>
	<delete beforeDelete="beforeDelete"></delete>
</pageDefinition>

=== DeffersonCheng/frame/schedule-application/src/main/java/com/frame/schedule/controller/taskController.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:noNamespaceSchemaLocation="/pageDefinition.xsd">
	<queryDefinition>
		<mappedClass mappedClass="com.frame.schedule.entity.TaskEntity">
		</mappedClass>
		<where>taskType='STATIC'</where>
		<sort>
			<by field="id" order="ASC"/>
		</sort>
		<columns>
			<column header="Id" field="id" width="10%" sortable="true" hidden="false"/>
			<column header="任务编码" field="taskCode" width="10%" sortable="true" hidden="false"/>
			<column header="任务名称" field="taskName" sortable="true" hidden="false"/>
			<column header="任务标签" field="taskTag " sortable="true" hidden="false"/>
			<column header="任务执行周期" field="taskCron" sortable="true" hidden="false"/>
			<column header="执行次数" field="execNum" sortable="true" hidden="false"/>
			<column header="状态" field="status" sortable="true" hidden="false"/>
		</columns>
		<searchDefinition>
			<condition field="taskCode" operator="LIKE" displayText="任务编码" inputType="TEXT"/>
			<condition field="taskName" operator="LIKE" displayText="任务名称" inputType="TEXT"/>
		</searchDefinition>
		<pageSize>10</pageSize>
        <js>
            <path>/resources/js/schedule/task-list.js</path>
        </js>
        <css>
        </css>
	</queryDefinition>
	<delete></delete>
	<manage>
		<field field="taskName" displayText="任务名称"/>
		<field field="taskTag" displayText="任务标签"/>
		<field field="taskCode" displayText="任务编码"/>
		<field field="taskCron" displayText="任务执行周期"/>
		<field field="paramTemplate" displayText="任务参数模板" inputType="TEXTAREA"/>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/webapp/controller/admin/video/adminVideoUploadDefinetion.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.media.VideoUploadEntity" alias="v">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.core.entity.UserEntity" alias="u">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<where>u.id=v.createUserKey</where>
		<sort>
			<by field="id" fromAlias="v" order="ASC"></by>
		</sort>

		<columns>
			<column header="ID" field="id" fromAlias="v" width="5%" sortable="true" hidden="false"></column>
			<column header="视频名称" field="videoName" fromAlias="v" width="15%" sortable="false" hidden="false"></column>
			<column header="视频链接" field="httpLink" fromAlias="v" width="20%" sortable="true" hidden="false"></column>
			<column header="视频新名字" field="videoNewName" fromAlias="v" width="15%" sortable="false" hidden="false"></column>
			<column header="上传人" field="nickName" fromAlias="u" width="10%" sortable="true" hidden="false"></column>
			<column header="描述 " field="description" fromAlias="v" width="20%" sortable="true" hidden="false"></column>
			<column header="上传日期" field="createDateTime" fromAlias="v" width="20%" sortable="true" hidden="false"></column>
		</columns>
		<searchDefinition>
			<condition alias="v" field="videoName" operator="LIKE" displayText="视频名称" inputType="TEXT"></condition>
			<condition alias="u" field="nickName" operator="LIKE" displayText="上传人" inputType="TEXT"></condition>
			<condition alias="v" field="createDateTime" operator="&gt;" displayText="创建日期" inputType="DATEBOX"></condition>
			<condition alias="v" field="createDateTime" operator="&lt;" displayText="至" inputType="DATEBOX"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/js/video/video-upload.js</path>
		</js>
		<css>
			<path>/resources/css/video/video-list.css</path>
		</css>
	</queryDefinition>
	<delete beforeDelete="beforeDelete"></delete>
	<manage beforeManage="beforeUpdate">
		<field field="videoName" inputId="videoName" displayText="视频名称" ></field>
		<field field="videoNewName" inputId="videoNewName" displayText="" ></field>
		<field field="description" inputId="description" displayText="视频描述" inputType="TEXTAREA"></field>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/js/dropzone/dropzone.js</path>
			<path>/resources/js/video/video-upload-add.js</path>
		</js>
		<css>
				<path>/resources/js/dropzone/dropzone.css</path>
		</css>
	</manage>
</pageDefinition>
