=== DeffersonCheng/frame/src/main/resources/pageDefinition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema id="pageDefinition" attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="pageDefinition" type="pageDefinitionType">
		<xs:annotation>
			<xs:documentation>
				随便写写
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="pageDefinitionType">
		<xs:sequence>
			<xs:element name="queryDefinition" minOccurs="1"
				maxOccurs="1" type="queryDefinitionType">
			</xs:element>
			<xs:element maxOccurs="1" minOccurs="0" name="delete" type="deleteType"/>
			<xs:element name="manage" type="manageType" maxOccurs="1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="searchDefinitionType">
		<xs:sequence minOccurs="1">
			<xs:element name="condition" type="conditionType">
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="conditionType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="staticData"/>
		</xs:sequence>
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="alias"/>
		<xs:attribute name="operator" use="required" type="operatorType">
		</xs:attribute>
		<xs:attribute name="defaultValue"/>
		<xs:attribute name="inputType" type="editorType">
		</xs:attribute>
		<xs:attribute name="displayText" use="required"/>
		<xs:attribute name="selectTextField"/>
		<xs:attribute name="selectValeField"/>
		<xs:attribute name="inputId"/>
		<xs:attribute name="optionClass"/>
		<xs:attribute name="nullable" type="xs:boolean"/>
	</xs:complexType>
	<xs:simpleType name="operatorType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="="/>
			<xs:enumeration value="LIKE"/>
			<!--<xs:enumeration value="BETWEEN"></xs:enumeration> -->
			<xs:enumeration value="&gt;"/>
			<xs:enumeration value="&lt;"/>
			<xs:enumeration value="&gt;="/>
			<xs:enumeration value="&lt;="/>
			<xs:enumeration value="!="/>
			<xs:enumeration value="&lt;&gt;"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="queryDefinitionType">
		<xs:sequence>
			<xs:element minOccurs="1" name="mappedClass" type="mappedClassType"/>
			<xs:element name="where" minOccurs="0"/>
			<xs:element minOccurs="0" name="sort" type="sortType"/>
			<xs:element name="columns" minOccurs="1" maxOccurs="1" type="columnsType"/>
			<xs:element minOccurs="0" maxOccurs="1" name="pageSize" type="xs:int"/>
			<xs:element maxOccurs="1" minOccurs="0" name="js" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="css" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="1" name="searchDefinition" type="searchDefinitionType"/>
		</xs:sequence>
		<xs:attribute name="showIndex"/>
	</xs:complexType>
	<xs:complexType name="sortType">
		<xs:sequence>
			<xs:element minOccurs="0" name="by" type="sortByType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="columnsType">
		<xs:sequence>
			<xs:element minOccurs="1" name="column" type="columnType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="sortByType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="fromAlias"/>
		<xs:attribute name="order" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="ASC" />
					<xs:enumeration value="DESC" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="columnType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="header"/>
		<xs:attribute name="fromAlias"/>
		<xs:attribute name="width"/>
		<xs:attribute name="sortable" type="xs:boolean"/>
		<xs:attribute name="hidden" type="xs:boolean"/>
		<xs:attribute name="filter"/>
		<xs:attribute name="staticColumnData"/>
	</xs:complexType>
	<xs:complexType name="mappedClassType">
		<xs:sequence minOccurs="0">
			<xs:element name="join" type="joinType">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="mappedClass" use="required"/>
		<xs:attribute name="alias"/>
	</xs:complexType>
	<xs:complexType name="joinType">
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="as"/>
		<xs:attribute name="type">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="LEFT" />
					<xs:enumeration value="INNER" />
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="manageType">
		<xs:sequence>
			<xs:element name="field" type="manageFieldType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="js" type="jscssType"/>
			<xs:element maxOccurs="1" minOccurs="0" name="css" type="jscssType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="jscssType">
		<xs:sequence minOccurs="1">
			<xs:element name="path"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="editorType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="TEXT" />
			<xs:enumeration value="NUMBER" />
			<xs:enumeration value="SELECT" />
			<xs:enumeration value="DATEBOX" />
			<xs:enumeration value="TEXTAREA" />
			<xs:enumeration value="CHECKBOX" />
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="deleteType">
	</xs:complexType>
	<xs:complexType name="manageFieldType">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="1" name="staticData"/>
		</xs:sequence>
		<xs:attribute name="field" use="required"/>
		<xs:attribute name="defaultValue"/>
		<xs:attribute name="inputType" type="editorType"/>
		<xs:attribute name="displayText" use="required"/>
		<xs:attribute name="selectTextField"/>
		<xs:attribute name="selectValeField"/>
		<xs:attribute name="inputId"/>
		<xs:attribute name="optionClass"/>
		<xs:attribute name="nullable" type="xs:boolean">
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== DeffersonCheng/frame/src/main/java/com/frame/webapp/controller/admin/img/adminImgUploadDefinetion.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.media.ImgEntity" alias="i">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.entity.media.ImgGroupEntity" alias="g">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.core.entity.UserEntity" alias="u">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<where>u.id=i.createUserKey and i.imgGroupKey=g.id</where>
		<sort>
			<by field="id" fromAlias="i" order="ASC"></by>
		</sort>

		<columns>
			<column header="ID" field="id" fromAlias="i" width="10%" sortable="true" hidden="false"></column>
			<column header="相册名称" field="imgGroupName" fromAlias="g" width="15%" sortable="false" hidden="false"></column>
			<column header="新名字" field="imgName" fromAlias="i" width="10%" sortable="true" hidden="false"></column>
			<column header="旧名字" field="imgOriginalName" fromAlias="i" width="10%" sortable="true" hidden="false"></column>
<!-- 			<column header="域名或ip" field="srcName" fromAlias="i" width="10%" sortable="true" hidden="false"></column>
 -->		<column header="相片预览" field="savePath" fromAlias="i" width="15%" sortable="true" hidden="false"></column>
			<column header="上传人" field="nickName" fromAlias="u" width="10%" sortable="true" hidden="false"></column>
			<column header="创建日期" field="createDateTime" fromAlias="i" width="20%" sortable="true" hidden="false"></column>
			<!-- <column header="操作" width="10%" sortable="false" hidden="false" staticColumnData="删除"></column> -->
		</columns>
		<searchDefinition>
			<condition alias="i" field="imgName" operator="LIKE" displayText="相片名称" inputType="TEXT"></condition>
			<condition alias="u" field="nickName" operator="LIKE" displayText="上传人" inputType="TEXT"></condition>
			<condition alias="i" field="createDateTime" operator="&gt;" displayText="创建日期" inputType="DATEBOX"></condition>
			<condition alias="i" field="createDateTime" operator="&lt;" displayText="至" inputType="DATEBOX"></condition>
			<condition alias="g" field="id" operator="LIKE" displayText="相册名称" inputType="SELECT" selectTextField="imgGroupName" selectValueField="id" optionClass="com.frame.entity.media.ImgGroupEntity"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/js/fancybox/js/jquery.fancybox.js</path>
			<path>/resources/js/img/img-list.js</path>
		</js>
		<css>
			<path>/resources/js/fancybox/css/jquery.fancybox.css</path>
			<path>/resources/css/img/img-list.css</path>
		</css>
	</queryDefinition>
	<delete beforeDelete="beforeDelete"></delete>
	<manage beforeManage="beforeUpdate">
		<field field="imgGroupKey" inputId="imgGroupKey" displayText="选择上传相册" inputType="SELECT" optionClass="com.frame.entity.media.ImgGroupEntity" selectTextField="imgGroupName" selectValeField="id"></field>
		<field field="imgOriginalName" inputId="imgOriginalName" displayText=""></field>
		<field field="imgName" inputId="imgName" displayText=""></field>
		<field field="srcName" inputId="imgupload" displayText="上传"></field>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/layui/layui.js</path>
			<path>/resources/js/dropzone/dropzone.js</path>
			<path>/resources/js/img/imgUpload.js</path>
		</js>
		<css>
			<!-- <path>/resources/layui/css/layui.css</path> -->
			<path>/resources/js/dropzone/dropzone.css</path>
		</css>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/schedule/controller/taskRecordController.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:noNamespaceSchemaLocation="/pageDefinition.xsd">
	<queryDefinition>
		<mappedClass mappedClass="com.frame.schedule.entity.TaskRecordEntity"
			alias="r" >
			<join type="LEFT" field="task" as="t" />
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" order="ASC"></by>
		</sort>
		<columns>
			<column header="Id" field="id" fromAlias="r" width="10%" sortable="true" hidden="false"/>
			<column header="任务名称" field="taskName" fromAlias="t" width="10%" sortable="true" hidden="false"/>
			<column header="执行编码" field="taskExecuteCode" fromAlias="r" width="10%" sortable="true" hidden="false"/>
			<column header="计划开始时间" field="planStartDate" fromAlias="r" sortable="true" hidden="false"/>
			<column header="实际开始时间" field="startDateTime" fromAlias="r" sortable="true" hidden="false"/>
			<column header="实际结束时间" field="finishDateTime" fromAlias="r" sortable="true" hidden="false"/>
			<column header="状态" field="status" fromAlias="r" sortable="true" hidden="false"/>
			<column header="创建时间" field="createDateTime" fromAlias="r" sortable="true" hidden="false"/>
			<column header="更新时间" field="updateDateTime" fromAlias="r" sortable="true" hidden="false"/>
		</columns>

		<searchDefinition>
            <condition alias="t" field="taskName" operator="LIKE" displayText="任务名称" inputType="TEXT"/>
            <condition alias="r" field="taskExecuteCode" operator="LIKE" displayText="执行编码" inputType="TEXT"/>
            <condition alias="r" field="planStartDate" operator="&gt;" displayText="计划开始时间" inputType="DATEBOX"/>
            <condition alias="r" field="planStartDate" operator="&lt;" displayText="到----" inputType="DATEBOX"/>
            <condition alias="t" field="id" operator="=" displayText="静态任务" selectTextField="taskName"
                       inputType="SELECT"/>
		</searchDefinition>
		<pageSize>10</pageSize>
        <js>
        </js>
        <css>
        </css>
	</queryDefinition>
	<delete></delete>
	<manage>
		<field field="taskExecuteCode" displayText="执行码"></field>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/webapp/controller/admin/editor/classDynamicDefinetion.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.entity.media.ClassDynamicEntity" alias="c">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<mappedClass mappedClass="com.frame.core.entity.UserEntity" alias="u">
			<!-- <join type="LEFT" field="parent" as="p" /> -->
		</mappedClass>
		<where>u.id=c.userId</where>
		<sort>
			<by field="createDateTime" fromAlias="c" order="DESC"></by>
		</sort>

		<columns>
			<column header="ID" field="id" fromAlias="c" width="10%" editorType="CHECKBOX" sortable="true" hidden="false"></column>
			<column header="创建 人" field="nickName" fromAlias="u" width="20%" sortable="true" hidden="false"></column>
			<column header="标题" field="title" fromAlias="c" width="20%" sortable="false" hidden="false"></column>
<!-- 			<column header="内容" field="content" fromAlias="c" width="20%" sortable="false" hidden="false"></column>
	 -->		<column header="创建日期" field="createDateTime" fromAlias="c" width="20%" sortable="true" hidden="false"></column>
			<!-- <column header="操作" width="10%" sortable="false" hidden="false" staticColumnData="删除"></column> -->
		</columns>
		<searchDefinition>
			<condition alias="c" field="id" operator="=" displayText="ID" inputType="NUMBER"></condition>
			<condition alias="c" field="userId" operator="LIKE" displayText="创建 人" inputType="SELECT" selectTextField="nickName" selectValueField="id" optionClass="com.frame.core.entity.UserEntity"></condition>
			<condition alias="c" field="createDateTime" operator="&gt;" displayText="创建日期" inputType="DATEBOX"></condition>
			<condition alias="c" field="createDateTime" operator="&lt;" displayText="至" inputType="DATEBOX"></condition>
			<condition alias="c" field="title" operator="LIKE" displayText="标题" inputType="TEXT"></condition><!-- selectTextField="createUserKey" inputType="SELECT" -->
		</searchDefinition>
		<pageSize>10</pageSize>
		<js>
		</js>
		<!-- <css><path>/a/b/c</path></css> -->
	</queryDefinition>
	<delete beforeDelete="beforeDelete"></delete>
	<manage beforeManage="beforeUpdate">
		<field field="title" inputId="edtitle" displayText="标题" ></field>
		<field field="id" inputId="edid" hidden="true" displayText="" ></field>
		<field field="content" inputId="edcontent" displayText="" inputType="TEXTAREA"></field>
		<js>
			<path>/resources/layer-v3.0.3/layer/layer.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/etpl 3-2-0.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/umeditor.config.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/umeditor.js</path>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/lang/zh-cn/zh-cn.js</path>
			<path>/resources/js/account/class-dynamic.js</path>
		</js>
		<css>
			<path>/resources/plugin/umeditor1_2_2-utf8-jsp/themes/default/css/umeditor-1-2-3.css</path>
		</css>
	</manage>
</pageDefinition>

=== DeffersonCheng/frame/schedule-core/src/main/java/com/frame/core/webapp/controller/account/pageDefinition.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.core.entity.UserEntity"
			alias="u" >
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" fromAlias="u" order="ASC"/>
		</sort>
		<columns>
			<column header="用户名" field="userLoginVerification" fromAlias="u" width="40%" sortable="true"
					hidden="false"/>
			<column header="昵称" field="nickName" fromAlias="u" width="40%" sortable="true" hidden="false"/>
		</columns>
		<searchDefinition>
			<condition alias="u" field="userLoginVerification" operator="LIKE" displayText="用户名" inputType="TEXT"/>
			<condition alias="u" field="nickName" operator="LIKE" displayText="昵称" inputType="TEXT"/>
		</searchDefinition>
		<pageSize>10</pageSize>
	</queryDefinition>
	<manage beforeManage="beforeUpdate">
		<field field="userLoginVerification" displayText="用户名"/>
		<field field="nickName" displayText="昵称"/>
		<field field="roles" displayText="拥有角色" inputType="CHECKBOX"
			   optionClass="com.frame.com.frame.core.entity.RoleEntity" selectTextField="name" selectValeField="id"/>
		<!-- <field field="file" displayText="附件" inputType="file"></field> -->
	</manage>
	<delete/>
</pageDefinition>

=== DeffersonCheng/frame/src/main/java/com/frame/demo/controller/studentController.xml
<?xml version="1.0" encoding="UTF-8"?>
<pageDefinition  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../core/query/xml/definition/pageDefinition.xsd">
	<queryDefinition showIndex="序号">
		<mappedClass mappedClass="com.frame.demo.entity.Student">
		</mappedClass>
		<where></where>
		<sort>
			<by field="id" order="ASC"></by>
		</sort>
		<columns>
			<column header="ID" field="id"  width="10%" sortable="true" hidden="false"></column>
			<column header="姓名" field="name" sortable="true" hidden="false"></column>
			<column header="学号" field="no" sortable="true" hidden="false"></column>
		</columns>
		<searchDefinition>
			<condition field="name" operator="LIKE" displayText="姓名" inputType="TEXT"></condition>
			<condition field="no" operator="=" displayText="学号" inputType="TEXT"></condition>
		</searchDefinition>
		<pageSize>10</pageSize>
	</queryDefinition>
	<delete></delete>
	<manage>
		<field field="name" displayText="姓名"></field>
		<field field="no" displayText="学号"></field>
	</manage>
</pageDefinition>
